server/gallery/models.py
from datetime import datetime
import urllib

from server.events.models import Event
from ..aws import upload_to_s3, delete_from_s3
from ..db import db, ActiveModel


# Images table
class Image(ActiveModel, db.Model):
    __tablename__ = 'images'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.String(510), nullable=False)
    path = db.Column(db.String(2083), nullable=False)
    event_id = db.Column(db.Integer, db.ForeignKey('events.id'))
    menu_id = db.Column(db.Integer, db.ForeignKey('menus.id'))
    created_at = db.Column(db.DateTime, nullable=False)
    small_path = db.Column(db.String(2083))

    event = db.relationship('Event', foreign_keys='Image.event_id', uselist=False, backref='images')
    menu = db.relationship('Menu', foreign_keys='Image.menu_id', uselist=False, backref='images')

    @property
    def filename(self):
        return urllib.unquote(self.path.split('gallery/')[1])

    @classmethod
    def create_image(cls, name, description, path, event_id=None, menu_id=None, **kwargs):
        image = cls()
        image.name = name
        image.description = description
        image.event_id = event_id
        image.menu_id = menu_id
        image.path = path
        image.created_at = datetime.utcnow()
        image.save(**kwargs)

        dest_path = 'gallery/{}_{}'.format(name.lower().replace(' ', '_'), image.id)
        key = upload_to_s3(dest_path, filename=path, policy='public-read')
        image.path = key.generate_url(expires_in=0, query_auth=False)
        image.save()

        return image

    @classmethod
    def random_image(cls):
        return cls.query.order_by(db.func.rand()).first()

    @classmethod
    def remove_event(cls, event_id):
        images = cls.query.filter(cls.event_id == event_id).all()
        for image in images:
            image.event_id = None
            image.save()

    @classmethod
    def remove_image(cls, image_id):
        image = cls.query.get(image_id)
        # Check for events that use image as cover
        # Just switch to random image for now
        # TODO: change to a default image
        rando = Image.random_image()
        for event in Event.query.filter(Event.image_id == image.id):
            event.image_id = rando.id
            event.save()
        if image:
            delete_from_s3(image.path)
            image.remove()

    @classmethod
    def get_gallery_pagination(cls, page, per_page=8):
        return cls.query.join(cls.events).group_by(cls.id).paginate(page, per_page=per_page)

    def data_filters(self):
        if self.event:
            return self.event.e_type.data_filter[1:]
        return ''

    def get_similar_images(self, limit=6):
        return Image.query.filter(Image.id != self.id, Image.event_id==self.event_id).limit(limit)

    def __repr__(self):
        return '<Image (id={}, name={})>'.format(self.id, self.name)

server/gallery/__init__.py
from .views import gallery

server/gallery/views.py
from flask import Blueprint, render_template, abort
from .models import Image
from ..events.models import EventType


gallery = Blueprint('gallery', __name__, template_folder='templates', url_prefix='/gallery')


@gallery.route('/')
def view_gallery():
    images = Image.get_gallery_pagination(1)
    event_types = EventType.query.all()
    return render_template('gallery/gallery.html', images=images, event_types=event_types)


@gallery.route('/view/<int:image_id>')
def gallery_item(image_id):
    image = Image.query.get(image_id)
    if not image:
        abort(404)
    return render_template('gallery/gallery_item.html', image=image)


# Ajax loaded images for jscroll
@gallery.route('/<int:page>')
def gallery_page(page=1):
    images = Image.get_gallery_pagination(page)
    return render_template('gallery/page.html', images=images)

server/gallery/templates/gallery/gallery.html
{% extends 'main_base.html' %}

{% block styles %}
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css' />
  <style>
    .loader{
      l: absolute;
      top: 50%;
      left: 50%;
      margin-left: 200px;
      margin-top: 50px;
      background-size: contain;
      height: 50px;
      width: 50px;
      animation:  elastic-rotation 1.33s cubic-bezier(0.680, -0.550, 0.265, 1.550) infinite;
      background-repeat: no-repeat;
      background-position: center center;
      background-image: url(http://images.clipartpanda.com/carrot-20clipart-carrots2.png);
    }

    @keyframes elastic-rotation {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }

    .load-text {
      margin-top:50px;
      margin-left:145px;
      color: #FF9933;
      font-size: 30px;
      font-family: 'Dancing Script';
    }

    .elips {
      color: #33CC33;
    }

    .one {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.0s;
        animation: dot 1.3s infinite;
        animation-delay: 0.0s;
    }

    .two {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.2s;
          animation: dot 1.3s infinite;
          animation-delay: 0.2s;
    }

    .three {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.3s;
         animation: dot 1.3s infinite;
         animation-delay: 0.3s;
    }

    @-webkit-keyframes dot {
          0% { opacity: 0; }
         50% { opacity: 0; }
        100% { opacity: 1; }
    }

    @keyframes dot {
          0% { opacity: 0; }
         50% { opacity: 0; }
        100% { opacity: 1; }
    }
  </style>
{% endblock styles %}

{% block content %}
  <div id="content-wrapper" class="wrapper">

    <div class="section-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <!-- Remove the .animated class if you don't want things to move -->
            <h1 class="animated slideInLeft"><span>Gallery</span></h1>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="btn-group gallery__nav" id="filters">
            <a href="#" class="btn btn-default" data-filter="*">All</a>
            {% for event_type in event_types %}
              <a href="#" class="btn btn-default" data-filter="{{ event_type.data_filter }}"><span class="hidden-xs">{{ event_type.name }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div> <!-- / .row -->

        <div class="row list-inline gallery-list infinite-scroll" id="isotope-container">

          {% for image in images.items %}
            <div class="col-sm-4 col-md-3 isotope-item {{ image.data_filters() }}">
              <div class="gallery__item">
                <a href="{{ url_for('.gallery_item', image_id=image.id) }}">
                  <div class="gallery-thumbnail">
                    <img class="img-responsive gallery-img" src="{{ image.small_path }}" alt="{{ image.name }}">
                  </div>
                  <div class="gallery-text">
                    <div class="gallery-title">{{ image.name }}</div>
                    {{ image.description }}
                  </div>
                </a>
              </div>
            </div>
          {% endfor %}

        </div> <!-- / .row -->

        {% if images.has_next %}
          <nav id="page_nav">
            <a href="{{ url_for('gallery.gallery_page', page=images.next_num) }}"></a>
          </nav>
        {% endif %}

    </div>

  <!-- <div class="loader"></div> -->
  <!-- <p class="load-text"><span class="one elips">.</span><span class="two elips">.</span><span class="three elips">.</span> Loading <span class="one elips">.</span><span class="two elips">.</span><span class="three elips">.</span></p> -->


    </div> <!-- / .container -->
  </div> <!-- / .wrapper -->
{% endblock content %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/imagesloaded.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.infinitescroll.min.js') }}"></script>

  <script>

    // $("#isotope-container").load("{{ url_for('gallery.gallery_page', page=images.next_num) }}",function(){
    //    $(this).fadeIn();
    // });

    $(function(){
      var $container = $('#isotope-container').imagesLoaded(function() {
        $container.isotope({
          itemSelector: '.isotope-item',
          layoutMode: 'fitRows'
        });
      });

      // filter items on button click
      $('#filters a').on('click', function() {
        var filterValue = $(this).attr('data-filter');
        $container.isotope({ filter: filterValue });
        return false;
      });

      $container.infinitescroll({
        navSelector: '#page_nav',
        nextSelector: '#page_nav a',
        itemSelector: '.isotope-item',
        loading: {
            finishedMsg: 'No more pages to load.',
            img: 'http://i.imgur.com/qkKy8.gif'
          }
        },
        // call Isotope as a callback
        function(newElements) {
          $container.isotope('appended', $(newElements));
          $container.imagesLoaded().progress( function() {
            $container.isotope('layout');
          });
        }
      );

    });

  </script>
{% endblock scripts %}

server/gallery/templates/gallery/gallery_item.html
{% extends 'main_base.html' %}

{% block content %}
<div class="wrapper">
  <div class="section-header">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <!-- Remove the .animated class if you don't want things to move -->
          <h1 class="animated slideInLeft"><span>{{ image.name }}</span></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-9">
        <div class="gallery-show">
          <div class="item active">
            <img src="{{ image.path }}" class="img-responsive" alt="...">
          </div>
        </div>
        <!-- New comment form -->
        <div class="new-comment">
          <div id="disqus_thread"></div>
          <script type="text/javascript">
              /* * * CONFIGURATION VARIABLES * * */
              var disqus_shortname = 'foodunderground';
              /* * * DON'T EDIT BELOW THIS LINE * * */
              (function() {
                  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
              })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
        </div>
      </div>
      <div class="col-sm-4 col-md-3">
        <h3>{{ image.name }}</h3>
        <p>{{ image.description }}</p>
        <hr>
        <h4>Similar Images</h4>
        <ul class="row list-inline gallery-list-small">
          {% for similar_image in image.get_similar_images() %}
            <li class="col-xs-3">
              <a href="{{ url_for('.gallery_item', image_id=similar_image.id) }}">
                <img class="img-responsive" src="{{ similar_image.path }}" alt="{{ similar_image.name }}">
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

server/gallery/templates/gallery/page.html
{% for image in images.items %}
  <div class="col-sm-4 col-md-3 isotope-item {{ image.data_filters() }}">
    <div class="gallery__item">
      <a href="{{ url_for('.gallery_item', image_id=image.id) }}">
        <div class="gallery-thumbnail">
          <img class="img-responsive gallery-img" src="{{ image.path }}" alt="{{ image.name }}">
        </div>
        <div class="gallery-text">
          <div class="gallery-title">{{ image.name }}</div>
          {{ image.description }}
        </div>
      </a>
    </div>
  </div>
{% endfor %}