server/events/views.py
from flask import Blueprint, render_template, abort, request
from .models import Event


events = Blueprint('events', __name__, template_folder='templates', url_prefix='/events')

@events.route('/')
@events.route('/<int:page>')
def list_events(page=1):
    year = request.args.get('year')
    month = request.args.get('month')
    events = Event.get_timeline_events(page, year, month)
    archive = Event.get_archive()
    return render_template(
        'events/events.html',
        events=events,
        archive=archive,
        request_year=int(year) if year else None,
        request_month=int(month) if month else None
    )

@events.route('/view/<int:event_id>')
def view_event(event_id):
    event = Event.query.get(event_id)
    if not event:
        abort(404)
    return render_template('events/view_event.html', event=event)

server/general/__init__.py
from .views import general

server/general/views.py
from flask import Blueprint, render_template
from ..events.models import Event
from ..gallery.models import Image


general = Blueprint('general', __name__, template_folder='templates')

@general.route('/')
def index():
    return render_template('general/index.html',
        recent_events=Event.get_recent_events(),
        upcoming_events=Event.get_upcoming_events())


@general.route('/team')
def team():
    return render_template('general/team.html')

@general.route('/contact')
def contact():
    return render_template('general/contact.html')


# Services
@general.route('/services')
def services():
    return render_template('general/services.html')

@general.route('/services/plated-dinners')
def services_plated_dinners():
    return render_template('general/plated_dinners.html')

@general.route('/services/workshops')
def services_workshops():
    return render_template('general/workshops.html')

@general.route('/services/cooks-canvas')
def services_cooks_canvas():
    return render_template('general/cooks_canvas.html')

@general.route('/services/popup-events')
def services_popup_events():
    return render_template('general/popup_events.html')

server/general/templates/general/contact.html
{% extends 'main_base.html' %}

{% block content %}
<div class="wrapper">
  <div class="section-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <!-- Remove the .animated class if you don't want things to move -->
          <h1 class="animated slideInLeft"><span>Contact Us</span></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <!-- Contact us form -->
      <div class="col-sm-8">
        <h2 class="hl top-zero">Contact Us</h2>
        <hr>
        <p>Have any questions or comments? Feel free drop us a line.</p>
        <!-- Alert message -->
        <div class="alert" id="form_message" role="alert"></div>
        <!-- Please carefully read the README.txt file in order to setup
             the PHP contact form properly -->
        <form role="form" id="form_sendemail" method="POST" action="{{ url_for('email.send_message') }}">
          <div class="form-group">
            <label for="email">Your email address</label>
            <input type="email" name="email" class="form-control" id="email" placeholder="E-mail" data-original-title="" title="">
            <span class="help-block"></span>
          </div>
          <div class="form-group">
            <label for="name">Your name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Full Name" data-original-title="" title="">
            <span class="help-block"></span>
          </div>
          <div class="form-group">
            <label for="message">Your message</label>
            <textarea name="message" class="form-control" rows="3" id="message" placeholder="Message"></textarea>
            <span class="help-block"></span>
          </div>
          <button type="submit" class="btn btn-dark">Contact Us</button>
        </form>
      </div>
      <!-- Right column -->
      <div class="col-sm-4">
        <!-- Out Info -->
        <h4>Our Info</h4>
        <hr>
        <p>
          Phone: (267) 713-2662<br />
          Email: <a href="#">info@foodunderground.net</a>
        </p>
        <hr>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

server/general/templates/general/cooks_canvas.html
{% extends 'main_base.html' %}

{% block styles %}
  <link href="{{ url_for('static', filename='css/custom/services.css') }}" rel="stylesheet">
{% endblock styles %}

{% block content %}
  <div class="wrapper">
    <div class="section-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <!-- Remove the .animated class if you don't want things to move -->
            <h1 class="animated slideInLeft"><span>Services - Cook's Canvas</span></h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="hl text-center top-zero">Cook's Canvas</h1>
          <p class="lead text-center">
            Restaurant work is hard work. Just ask any cook about their long, demanding hours and grueling work week. But it's during that time when a cook is exposed to myriad ingredients, techniques, and styles - stimulating their creative minds. Though, most never get the chance to implement all those ideas or to execute their culinary visions. Cooks' Canvas showcases such line cooks of great promise, affording them the opportunity to realize their imaginations by providing an audience to feed. In turn, the guests then feed these young cooks' futures. This all happens in tandem with the Food Underground staff. We facilitate the framework in which dream becomes reality, connecting these aspiring artists and their patrons.
            <br /><br />
            Click <a href="{{ url_for('events.list_events') }}">here</a> to see upcoming cooks canvas events.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="about-btn">
            <a class="btn btn-default" href="{{ url_for('general.services') }}">Back to Services</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

server/general/templates/general/index.html
{% extends 'main_base.html' %}

{% block content %}
<div class="wrapper">
  <div id="wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <h1 class="animated slideInDown">Food Underground</h1>
          <div class="list">
            <ul>
              <li class="animated slideInLeft first delay fancy">A tasteful blend of food and writing</span></li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 hidden-sm hidden-xs">
          <div class="showcase">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Pen and Knife" class="penAndKnife animated fadeInDown">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <div class="row">

      <!-- UPCOMING -->
      <div class="col-md-4">
        <div class="block-header">
          <h2>
            <span class="title">Upcoming Public Events</span><span class="decoration"></span><span class="decoration"></span><span class="decoration"></span>
          </h2>
        </div>
        <div class="tab-content">
          {% if upcoming_events %}
            {% for event in upcoming_events %}
              <h5><a href="{{ url_for('events.view_event', event_id=event.id) }}">{{ event.name }}</a> <small>{{ event.date }}</small></h5>
              {% if event.description %}
                <p class="text-muted"><small>{{ event.description }}</small></p>
              {% endif %}
              {% if event.location %}
                <p class="text-muted"><i class="fa fa-map-marker"></i> {{ event.location }}</p>
              {% endif %}
              <hr>
            {% endfor %}
          {% else %}
            <h5>No upcoming events.</h5>
          {% endif %}
        </div>
      </div>

      <!-- RECENT EVENTS -->
      <div class="col-md-8">
        <div class="block-header">
          <h2>
            <span class="title">Recent Events</span><span class="decoration"></span><span class="decoration"></span><span class="decoration"></span>
          </h2>
        </div>

        {% for event_group in recent_events %}
          <div class="row">
            {% for recent_event in event_group %}
            <div class="col-md-6 col-sm-6">
              <div class="thumbnail">
                <img src="{{ recent_event.cover_image.path }}" class="img-responsive" alt="{{ recent_event.cover_image.name }}">
                <div class="visit"><a href="{{ url_for('events.view_event', event_id=recent_event.id) }}"><i class="fa fa-question-circle"></i> More details...</a></div>
                <div class="caption">
                  <h4>{{ recent_event.name }}</h4>
                  <p>{{ recent_event.description }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        {% endfor %}

      </div>

    </div>

    <!-- ABOUT -->
    <div class="row">
      <div class="col-md-12 block-header">
        <h2>
          <span class="title">About Food Underground</span><span class="decoration"></span><span class="decoration"></span><span class="decoration"></span>
        </h2>
        <p>Food Underground is plated dinners for those special occasions that demand elegance and sophistication. It is family style meals to celebrate the people and moments that make up your life. It is supporting the next generation of great chefs, who have yet to step off the line and into their futures. And, it is the written word, telling the story of our culinary experience and beyond.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 block-header">
        <h2>
          <span class="title"><a href="http://instagram.com/foodunderground" target="_blank">@foodunderground</a> on Instagram</span><span class="decoration"></span><span class="decoration"></span><span class="decoration"></span>
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 block-header">
         <div id="instafeed">
          <ul class="instalist"></ul>
         </div>
      </div>
    </div>

  </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/spectagram.js') }}"></script>
<script type="text/javascript">
  jQuery.fn.spectragram.accessData = {
      accessToken: '823477839.89236a7.692bb233be3f43c9a7bc3ce86774c69f',
      clientID: '89236a75c789466ca02796fdf954914d'
  };
  $('#instafeed .instalist').spectragram('getRecentMedia', {
      user_id: '823477839',
      size: 'small',
      max: 21
  });
</script>
{% endblock scripts %}

server/general/templates/general/plated_dinners.html
{% extends 'main_base.html' %}

{% block styles %}
  <link href="{{ url_for('static', filename='css/custom/services.css') }}" rel="stylesheet">
{% endblock styles %}

{% block content %}
  <div class="wrapper">
    <div class="section-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <!-- Remove the .animated class if you don't want things to move -->
            <h1 class="animated slideInLeft"><span>Services - Restaurant Experience</span></h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="hl text-center top-zero fancy">Restaurant Experience</h1>
          <p class="lead text-center">
            There are times when a celebration calls for elegance in food, atmosphere, and detail. Food Underground brings this to you. Be it in your home or at your special venue of choice, Food Underground is the restaurant experience custom tailored to your unique occasion. We bring an array of seasonal products – including produce, meat, seafood, and fish – with creative and beautiful presentation. We set your table with our plates and flatware, on our linens. And just as our chef plates your meal with an eye for detail and beauty, our professional server tends to your needs tableside.
          <br /><br />
            These are three signature menus that provide a Food Underground culinary experience.  We can also modify these menus to match your tastes or create a unique menu from scratch designed to compliment the occasion.  All you have to do is ask!
          </p>
          <br />
        </div>
      </div>
       <div class="row pricing">
        <div class="col-sm-4">
          <!-- Remove .animated .fadeInDown .first classes if you don't want item to move -->
          <div class="item animated fadeInDown first">
            <div class="head" style="margin-bottom:10px">
              <h4 class="fancy">A Walk Around Philly</h4>
            </div>
            <div class="sceleton">
            <ul>
              {% filter title %}
                <li><strong> Cocoa Nib Scrapple</strong><br /><em> Housemade pretzel | Quail egg | Coffee maple</em></li>
                <li><strong> Vietnamese Pork Roll Tamale</strong><br /><em> Pickled carrots and radish | Spicy cucumber</em></li>
                <li><strong> Italian "Hoagie"</strong><br /><em> Heirloom tomato | Fried oregano | Basil oil | Pepperoni | Long hot relish | Provolone chips</em></li>
                <li><strong> African Chicken</strong><br /><em> Couscous | Date vinaigrette | Stone fruit</em></li>
                <li><strong> broccoli rabe gnocchi</strong><br /><em> pork scallopini | lemon and sage butter</em></li>
                <li><strong> flight of water ice</strong><br /><em> cilantro vanilla | anise and almond | chocolate and chili</em></li>
              {% endfilter %}
            </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="item animated fadeInDown second">
            <div class="head" style="margin-bottom:10px">
              <h4 class="fancy">Tel Aviv Story Tellers</h4>
            </div>
            <div class="sceleton">
            <ul>
              {% filter title %}
                <li><strong> housemade pretzel bite</strong><br /><em> roasted cherry tomato | seared haloumi | pepperoni</em></li>
                <li><strong> watermelon and raw shrimp</strong><br /><em> arak | mint | preserved lemon | bird chili schug</em></li>
                <li><strong> cured sardine bruschetta</strong><br /><em> olives | pistachio | purslane | Bulgarian feta stuffed long hot</em></li>
                <li><strong> sabih gyuniku</strong><br /><em> Arabic salad | mint tahina | crispy potatoes | Iraqi egg</em></li>
                <li><strong> chicken hearts and lamb fat</strong><br /><em> green hummus | fresh laffa | grapes</em></li>
                <li><strong> Tel Aviv nights</strong><br /><em> matcha green tea semolina | jasmine creme</em></li>
              {% endfilter %}
            </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="item animated fadeInDown third">
            <div class="head" style="margin-bottom:10px">
              <h4 class="fancy">Food Underground Classics</h4>
            </div>
            <div class="sceleton">
            <ul>
              {% filter title %}
                <li><strong> cured mussels</strong><br /><em> bruschetta | cured egg yolk | arugula pesto</em></li>
                <li><strong> caprese</strong><br /><em> fresh burrata | tomato water | basil noodles | tomato jam</em></li>
                <li><strong> beer bread french toast</strong><br /><em> duck breast | quail’s egg | crispy leeks | mustard gastrique</em></li>
                <li><strong> Russian Pasta</strong><br /><em> cured fish | chive pasta | dill oil | parsley leaf | charred fennel</em></li>
                <li><strong> homemade mint ice cream</strong><br /><em> brownie crumble | delicate almond cookie | fresh fruit</em></li>
              {% endfilter %}
            </ul>
            </div>
          </div>
        </div>
      </div>

      <br /><br />

      <div class="row">
        <div class="col-md-12">
          <p class="lead text-center">
            Click <a href="{{ url_for('general.contact') }}">here</a> to contact us to bring the restaurant experience to you!
          </p>
          <br />
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="about-btn">
            <a class="btn btn-default" href="{{ url_for('general.services') }}">Back to Services</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

server/general/templates/general/popup_events.html
{% extends 'main_base.html' %}

{% block styles %}
  <link href="{{ url_for('static', filename='css/custom/services.css') }}" rel="stylesheet">
{% endblock styles %}

{% block content %}
  <div class="wrapper">
    <div class="section-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <!-- Remove the .animated class if you don't want things to move -->
            <h1 class="animated slideInLeft"><span>Services - Pop Ups</span></h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="hl text-center top-zero">Pop Up Events</h1>
          <p class="lead text-center">
            Here at Food Underground we like to cook.  A lot.  This passion provides us a unique opportunity to showcase our food in many different and exciting venues around the city.  The best part is that these events are all public so that means you can easily immerse yourself in the Food Underground experience!  All you need to do is stay in touch.  The best way to do that?  By clicking <a class="subscribe-link" href="#">here</a> to sign up for the monthly mailing list or <a href="{{ url_for('events.list_events') }}">here</a> to see a list of upcoming events.
          </p>
          <br />
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="about-btn">
            <a class="btn btn-default" href="{{ url_for('general.services') }}">Back to Services</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

server/general/templates/general/workshops.html
{% extends 'main_base.html' %}

{% block styles %}
  <link href="{{ url_for('static', filename='css/custom/services.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/tooltipster.css') }}" rel="stylesheet">
{% endblock styles %}

{% block content %}
  <div class="wrapper">
    <div class="section-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <!-- Remove the .animated class if you don't want things to move -->
            <h1 class="animated slideInLeft"><span>Services - Workshops</span></h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="hl text-center top-zero fancy">Hands On Workshops</h1>
          <p class="lead text-center">
            Want to sharpen your chops in the kitchen?  Food Underground has you covered.  Have us over to get a hands on cooking experience where you will surely pick up some new tricks and technique.  Whether you’re just learning to hold a knife, or you want to perfect your brunoise we can help!  Take a look at our classes below.  If you dont see anything that fits your needs, be in touch and we’ll cook something up, customized just for you.
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="services">
            <div class="services__item quarter_service">
              <div id="tip-1" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-sprig2 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Pasta Basics</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-2" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-spaghetti3 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Advanced Pasta</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-3" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-spaghetti1 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Pasta: Crazy</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-4" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-salad fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Mezze</p>
                  <p class="services-item__link">The Staples</a>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div> <!-- / .services -->
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="services">
            <div class="services__item quarter_service">
              <div id="tip-5" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-cooking37 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Tailgating</p>
                  <p class="services-item__link">Next Level</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-6" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-turkey7 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Tailgating II</p>
                  <p class="services-item__link">Next Next Level</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-7" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-icecreams14 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Ice Cream</p>
                  <p class="services-item__link">And Pretzels!</p>
                </div>
              </div>
            </div>
            <div class="services__item quarter_service">
              <div id="tip-8" class="services-item__body tooltipster">
                <i class="services-item__icon fa flaticon-wine47 fa-3x"></i>
                <div class="services-item__content">
                  <p class="services-item__caption fancy">Market to Table</p>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
          </div> <!-- / .services -->
        </div>
      </div>

      <br /><br />
      <div class="row">
        <div class="col-md-12">
          <p class="lead text-center">
              Unless otherwise noted all classes will last for 2 hours. One on one classes are $200 / class plus $75 / hour.
              Each additional participant is $75. All classes can be taught in group format.
              <br /><br />
              Don’t see what you’re looking for?
              Just let us know and we’ll design something custom
              fit for your needs. Additional food costs and travel fees may apply.
              <br /><br />
              Click <a href="{{ url_for('general.contact') }}">here</a> to tell us more and schedule a class.
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="about-btn">
            <a class="btn btn-default" href="{{ url_for('general.services') }}">Back to Services</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script type="text/javascript" src="{{  url_for('static', filename='js/jquery.tooltipster.min.js') }}"></script>
  <script>
    $(document).ready(function() {

      $('.tooltipster').tooltipster({
          maxWidth: 500
      });

      // Probably not the best way to do this but whatever
      $('#tip-1').tooltipster('content', $("<div style='text-align:center'>In this class our chef teaches you how to make perfect egg pasta dough. This provides you with the platform to make hundreds of different pastas, from farfalle to garganelli and even lorighittas! We then finish the class with our pasta two ways – learning to make a classic and versatile butter sauce and a hearty, seasonal ragu. You now have a whole arsenal of meals that will impress as much as they will sate.</div>"));
      $('#tip-2').tooltipster('content', $("<div style='text-align:center'>Here, our chef builds off the basic egg dough, with some cool twists. First, learn the impressive technique of lamination, using fresh herbs and flowers to beautiful effect. Then, using the laminated sheets, we make filled pastas (tortellini, ravioli, caramelle, agnilotti, etc.) using filling that we make together. To finish, we cook, sauce, and eat – just like they do in Italy!</div>"));
      $('#tip-3').tooltipster('content', $("<div style='text-align:center'>Let’s forget tradition and with some unexpected pastas! First, our chef teaches you how to make dough using fresh vegetable juice for the likes of orange, carrot pasta or purple, beet pasta. Then, we’ll make a signature Food Underground dish that not only has coffee in the pasta dough, but is boiled in coffee, too! To finish this savory dish, you’ll learn to caramelize cream, taking the cappuccino out of your mug and onto your plate.</div>"));
      $('#tip-4').tooltipster('content', $("<div style='text-align:center'>Traditional to Middle Eastern and Mediterranean culinary cultures, mezze is a series of small plates that satisfy the soul as much as the stomach. Our chef teaches you to make three dishes that can be served in this style such as hummus, burnt babaganoush, beet tabouleh, amba tahini wings, fish kebabs and yogurt, and so many more. No matter which specific mezze you learn, we’ll also make handmade laffa bread – an absolute necessity.</div>"));
      $('#tip-5').tooltipster('content', $("<div style='text-align:center'>Everyone does it, our chef teaches you how to do it better. In this first part of a series: wings. Though it’s traditional to fry them, our chef shows you how to achieve golden bliss by way of the oven. Then we make scratch BBQ sauce, cause your wings deserve the best. And since it’s best to fry something, we’ll make homemade potato chips. They can be tossed in anything you like, such as vinegar powder, celery salt, or some third option that you tell us about.</div>"));
      $('#tip-6').tooltipster('content', $("<div style='text-align:center'>With appetite whet from the wing appetizer, it’s time to break out the big guns and learn to make some sausage. Utilizing the Kitchen Aid meat grinder, our chef teaches you to season and emulsify in old world style. Then, learn to prepare and stuff natural casing for the most authentic finished product. After we twist links, learn to prepare the sausage on caste iron or grill. Then we’ll make beer mustard that we’ll make into mustard slaw to pair with your sausage. Hero status, there you are.</div>"));
      $('#tip-7').tooltipster('content', $("<div style='text-align:center'>Food Underground takes our ice cream as seriously as it does our pretzels. In this class, we'll knead, roll, boil, and bake our dough to pretzel perfection. Then, we’ll make ice cream base that starts with the best yolks and cream in the land. And, no matter what the flavor you choose – from vanilla or mint chocolate chip to earl grey or whiskey – you have the basics to make them all. So from the conclusion of this class on forward, your life is better. It’s as simple as that.</div>"));
      $('#tip-8').tooltipster('content', $("<div style='text-align:center'>This workshop begins at your grocery store where our chef shows you to navigate the aisles with confidence and select the best ingredients. It’s then off to your kitchen where the bagged bounty will be transformed into that night’s dinner. The menu is conceived on the fly and executed with skillful perfection with attention to efficiency and ease. You finish your meal not just a stronger cook, but a savvier shopper, better able to identify the freshest product that the season has to offer, be it fish, meat, cheese, or produce. This meal - appetizer, entree, side dish, and desert – takes 4 hours (estimated) from start to finish.</div>"));

    });
  </script>
{%  endblock scripts %}