server/events/models.py
import itertools
from datetime import datetime, date
from calendar import month_abbr
from ..db import db, ActiveModel


class Event(ActiveModel, db.Model):
    __tablename__ = 'events'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.String(765), nullable=False)
    location = db.Column(db.String(128))
    date = db.Column(db.Date, nullable=False)
    event_type = db.Column(db.Integer, db.ForeignKey('event_types.id'), nullable=False)
    image_id = db.Column(db.Integer, db.ForeignKey('images.id'), nullable=False)
    menu_id = db.Column(db.Integer, db.ForeignKey('menus.id'))
    bpt_id = db.Column(db.Integer)
    public = db.Column(db.Boolean, nullable=False, default=True)
    active = db.Column(db.Boolean, nullable=False, default=True)
    archived = db.Column(db.Boolean, nullable=False, default=False)

    cover_image = db.relationship('Image', foreign_keys='Event.image_id', uselist=False, backref='events')
    e_type = db.relationship('EventType', foreign_keys='Event.event_type', uselist=False, backref='events')

    @classmethod
    def get_recent_events(cls, limit=4):
        today = datetime.now().strftime('%Y-%m-%d')
        recent_events = iter(
            cls.query
                .filter(cls.date < today, cls.active == True, cls.archived == False)
                .order_by(cls.date.desc())
                .limit(limit)
        )

        # Group recent events into tuples of 2
        while True:
            chunk = tuple(itertools.islice(recent_events, 2))
            if not chunk:
                return
            yield chunk

    @classmethod
    def get_upcoming_events(cls, limit=5):
        today = datetime.now().strftime('%Y-%m-%d')
        return (
            cls.query
                .filter(cls.date >= today, cls.active == True, cls.archived == False)
                .order_by(cls.date)
                .limit(limit)
        )

    @classmethod
    def random_event(cls):
        return cls.query.order_by(db.func.rand()).first()

    @classmethod
    def get_archive(cls):
        """Get data structure for date archive output
        :return: { year: { month: (month_abbr, count) }}
        """
        archive = {}
        results = db.session.query(db.func.year(cls.date), db.func.month(cls.date), db.func.count(cls.id)). \
            filter(cls.active == True, cls.archived == False). \
            group_by(db.func.year(cls.date), db.func.month(cls.date))

        for row in results:
            year = archive.setdefault(row[0], {})
            year[row[1]] = (month_abbr[row[1]], row[2])

        return archive

    @classmethod
    def get_timeline_events(cls, page=1, year=None, month=None):
        events = cls.query.filter(cls.active == True, cls.archived == False)
        if year:
            events = events.filter(db.func.extract('year', cls.date) == year)
        if month:
            events = events.filter(db.func.extract('month', cls.date) == month)
        return events.order_by(Event.date.desc()).paginate(page, 4)

    def is_upcoming(self):
        return self.date >= date.today()

    def gallery_images(self):
        for image in self.images:
            yield image
        yield self.cover_image

    def format_date(self, format='%b %d, %Y'):
        return self.date.strftime(format)

    def get_similar_events(self, limit=6):
        return Event.query.filter(
            Event.id != self.id,
            Event.event_type == self.event_type,
            Event.active == True,
            Event.archived == False).limit(limit)

    def __repr__(self):
        return '<Event {}>'.format(self.name)


class EventType(ActiveModel, db.Model):
    __tablename__ = 'event_types'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    description = db.Column(db.String(255))

    @property
    def data_filter(self):
        return '.cat-{}'.format(self.name.lower().replace(' ', '-'))

    def __repr__(self):
        return '<Event Type {}>'.format(self.name)

server/dash/forms.py
from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, IntegerField, DateField, BooleanField, SelectField
from wtforms.validators import DataRequired, Optional

from ..events.models import Event, EventType
from ..gallery.models import Image
from ..menus.models import Menu


class BaseFoodUndergroundForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])


class AddChoicesMixin():
    def add_event_choices(self):
        self.event_id.choices = [(e.id, e.name) for e in Event.query.order_by('name')]

    def add_menu_choices(self):
        self.menu_id.choices = [(m.id, m.name) for m in Menu.query.order_by('name')]

    def add_image_choices(self):
        self.image_id.choices = [(i.id, i.name) for i in Image.query.order_by('name')]


### Images ###

class UploadImageForm(BaseFoodUndergroundForm):
    image = FileField('Image', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png', 'jpeg'], 'JPG or PNG only!')
    ])


class EditImageForm(AddChoicesMixin, BaseFoodUndergroundForm):
    event_id = SelectField('Event', validators=[Optional()], coerce=int)
    menu_id = SelectField('Menu', validators=[Optional()], coerce=int)


### Events ###

class EventForm(AddChoicesMixin, BaseFoodUndergroundForm):
    date = DateField('Date', validators=[DataRequired()], format='%m/%d/%Y')
    location = StringField('Location', validators=[Optional()])
    event_type = SelectField('Event Type', validators=[DataRequired()], coerce=int)
    image_id = SelectField('Image', validators=[DataRequired()], coerce=int)
    menu_id = IntegerField('Menu', validators=[Optional()])
    bpt_id = IntegerField('Brown Paper Ticket ID', validators=[Optional()])
    public = BooleanField('Public', validators=[Optional()], default='checked')
    active = BooleanField('Active', validators=[Optional()], default='checked')

    def add_event_type_choices(self):
        self.event_type.choices = [(et.id, et.name) for et in EventType.query.order_by('name')]


### Menus ###

class MenuForm(AddChoicesMixin, Form):
    name = StringField('Name', validators=[DataRequired()])
    event_id = SelectField('Event', validators=[DataRequired()], coerce=int)
    image_id = IntegerField('Image', validators=[Optional()])


class CourseForm(AddChoicesMixin, Form):
    menu_id = SelectField('Menu', validators=[DataRequired()], coerce=int)
    description = StringField('Description', validators=[DataRequired()])
    course_order = ()
    image_id = IntegerField('Image', validators=[Optional()])


### Issues ###

class IssueForm(Form):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    priority = SelectField('Priortity', choices=[
        ('trivial', 'trivial'),
        ('minor', 'minor'),
        ('major', 'major'),
        ('critical', 'critical'),
        ('blocker', 'blocker')
    ])
    kind = SelectField('Kind', choices=[
        ('bug', 'bug'),
        ('enhancement', 'enhancement'),
        ('proposal', 'proposal'),
        ('task', 'task')
    ])

server/admin/views.py
from flask import Blueprint, redirect, request, render_template, url_for
from flask.ext.login import current_user, LoginManager, login_required, login_user, logout_user
from .models import Admin


admin = Blueprint('admin', __name__, template_folder='templates')
login_manager = LoginManager()


# Authorization via login manager
@login_manager.user_loader
def load_user(user_id):
    return Admin.query.get(user_id)


@admin.route('/login', methods=['GET', 'POST'])
def send_message():
    if current_user.is_authenticated():
        return redirect(url_for('dash.overview'))

    if request.method == 'POST':
        admin = Admin.authenticate_user(request.form['email'], request.form['password'])
        if not admin:
            # Incorrect email/password
            pass
        else:
            remember = request.form.get('remember') == 'on'
            login_user(admin, remember=remember)
            return redirect(url_for('dash.overview'))

    return render_template('admin/login.html')


@admin.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('general.index'))

server/dash/__init__.py
from .views import dash

server/dash/views.py
import os
from flask import Blueprint, render_template, url_for, redirect, flash, current_app, request, jsonify
from flask.ext.login import login_required
from werkzeug import secure_filename
from .forms import UploadImageForm, EditImageForm, EventForm, MenuForm, IssueForm
from ..bitbucket import post_new_issue
from ..events.models import Event
from ..gallery.models import Image
from ..menus.models import Menu
from ..service_account import get_access_token

from server.upload_file import uploadfile

dash = Blueprint('dash', __name__, template_folder='templates', url_prefix='/dash')

ALLOWED_EXTENSIONS = ('png', 'jpg', 'jpeg', 'gif')


@dash.route('/')
@login_required
def overview():
    ga_service_token = get_access_token(current_app)
    return render_template('dash/overview.html', ga_service_token=ga_service_token)


### Events ###

@dash.route('/events')
@dash.route('/events/<int:page>')
@login_required
def list_events(page=1):
    search_query = request.args.get('search')
    events = Event.query.filter(Event.archived==False)
    if search_query:
        events = events.filter(Event.name.like('%{}%'.format(search_query)))
    events = events.paginate(page, per_page=10)
    return render_template('dash/events.html', events=events, search_query=search_query)


@dash.route('/events/add', methods=['GET', 'POST'])
@login_required
def add_event():
    form = EventForm()
    form.add_image_choices()
    form.add_event_type_choices()
    if form.validate_on_submit():
        event = Event(
            name=form.name.data,
            description=form.description.data,
            location=form.location.data,
            date=form.date.data,
            event_type=form.event_type.data,
            image_id=form.image_id.data,
            menu_id=form.menu_id.data,
            active=form.active.data,
            bpt_id=form.bpt_id.data
        )
        event.save()
        return redirect(url_for('.edit_event', event_id=event.id))
    return render_template('dash/add_event.html', form=form)


@dash.route('/events/edit/<int:event_id>', methods=['GET', 'POST'])
@login_required
def edit_event(event_id):
    event = Event.query.get(event_id)
    form = EventForm(obj=event)
    form.add_image_choices()
    form.add_event_type_choices()
    if form.validate_on_submit():
        form.populate_obj(event)
        event.save()
        flash('Successfully updated event: {}'.format(event.name), category='info')
    return render_template('dash/edit_event.html', event=event, form=form)


@dash.route('/events/archive/<int:event_id>', methods=['POST'])
@login_required
def archive_event(event_id):
    event = Event.query.get(event_id)
    if event:
        event.archived = True
        event.save()
        Image.remove_event(event_id)
    return redirect(url_for('.list_events'))


### Images ###

@dash.route('/images')
@dash.route('/images/<int:page>')
@login_required
def list_images(page=1):
    search_query = request.args.get('search')
    images = Image.query
    if search_query:
        images = images.filter(Image.name.like('%{}%'.format(search_query)))
    images = images.paginate(page, per_page=10)
    return render_template('/dash/list_images.html', images=images, search_query=search_query)


@dash.route('/images/add', methods=['GET', 'POST'])
@login_required
def add_image():
    form = UploadImageForm()
    if request.method == 'POST': #  if form.validate_on_submit():
        image_file = request.files['file']
        filename = secure_filename(image_file.filename)
        full_path = '/tmp/{}'.format(filename)  # TODO - use os join
        image_file.save(full_path)
        image = Image.create_image(name=form.name.data, description=form.description.data, path=full_path)
        # get file size after saving
        size = os.path.getsize(full_path)
        # return json for js call back
        result = uploadfile(name=image.path, type=image_file.content_type, size=size)
        return jsonify(files=result.get_file())

    return render_template('dash/add_image.html', form=form)


@dash.route('/images/edit/<int:image_id>', methods=['GET', 'POST'])
@login_required
def edit_image(image_id):
    image = Image.query.get(image_id)
    form = EditImageForm(obj=image)
    form.add_event_choices()
    form.add_menu_choices()
    if form.validate_on_submit():
        form.populate_obj(image)
        image.save()
        flash('Successfully updated image: {}'.format(image.name), category='info')
    return render_template('dash/edit_image.html', image=image, form=form)


@dash.route('/images/remove/<int:image_id>', methods=['POST'])
@login_required
def remove_image(image_id):
    Image.remove_image(image_id)
    return redirect(url_for('.list_images'))

### Menus ###

@dash.route('/menus')
def list_menus():
    menus = Menu.query.all()
    return render_template('/dash/list_menus.html', menus=menus)


@dash.route('/menus/add', methods=['GET', 'POST'])
@login_required
def add_menu():
    form = MenuForm()
    if form.validate_on_submit():
        menu = Menu()
        menu.save()
        return redirect(url_for('.edit_menu', menu_id=menu.id))
    images = Image.query.all()
    return render_template('dash/add_menu.html', form=form, images=images)


@dash.route('/menus/<int:menu_id>', methods=['GET', 'POST'])
def edit_menu(menu_id):
    menu = Menu.query.get(menu_id)
    form = MenuForm(obj=menu)
    form.add_event_choices()
    if form.validate_on_submit():
        form.populate_obj(menu)
        menu.save()
        flash('Successfully updated {}'.format(menu.name))
    return render_template('dash/edit_menu.html', menu=menu, form=form)


### Issues ###

@dash.route('/issues', methods=['GET', 'POST'])
def issues():
    form = IssueForm()
    if form.validate_on_submit():
        post_new_issue(form.title.data, form.description.data, form.priority.data, form.kind.data)
        flash('Successfully posted the new issue')
    return render_template('dash/issues.html', form=form)

server/events/__init__.py
from .views import events

server/events/views.py
from flask import Blueprint, render_template, abort, request
from .models import Event


events = Blueprint('events', __name__, template_folder='templates', url_prefix='/events')

@events.route('/')
@events.route('/<int:page>')
def list_events(page=1):
    year = request.args.get('year')
    month = request.args.get('month')
    events = Event.get_timeline_events(page, year, month)
    archive = Event.get_archive()
    return render_template(
        'events/events.html',
        events=events,
        archive=archive,
        request_year=int(year) if year else None,
        request_month=int(month) if month else None
    )

@events.route('/view/<int:event_id>')
def view_event(event_id):
    event = Event.query.get(event_id)
    if not event:
        abort(404)
    return render_template('events/view_event.html', event=event)

server/dash/templates/dash/add_event.html
{% extends 'dash/base.html' %}

{% set dash_title = 'Add Event' %}
{% set dash_menu = 'events' %}

{% block styles %}
<link href="{{ url_for('static', filename='css/bootstrap/bootstrap-datepicker.min.css') }}" rel="stylesheet">
{% endblock styles %}

{% block dash_content %}
<div class="col-sm-8 col-md-6">
  <h3 class="hl">Add a new event</h3>
  <hr>
  <form role="form" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      <label for="name">Event name *</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Name of event">
    </div>

    <div class="form-group">
      <label for="event_type">Event Type *</label>
      <select class="form-control" id="event_type" name="event_type">
        {% for event_type in form.event_type.iter_choices() %}
          <option value="{{ event_type[0] }}" {{ 'selected' if event_type[2] else '' }}>{{ event_type[1] }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="description">Description *</label>
      <input type="text" class="form-control" id="description" name="description" placeholder="Brief description of the event">
    </div>

      <div class="form-group">
      {{ form.location.label }}
      {{ form.location(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.date.label }} *
      {{ form.date(class='form-control') }}
    </div>

    <div class="form-group">
      <label for="image_id">Cover Image *</label>
      <select class="form-control" id="image_id" name="image_id">
        {% for image in form.image_id.iter_choices() %}
          <option value="{{ image[0] }}" {{ 'selected' if image[2] else '' }}>{{ image[1] }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="menu">Menu</label>
      <select class="form-control" id="menu_id" name="menu_id">
        <option value="" selected="selected">No associated menu</option>
        {% for menu in menus %}
          <option value="{{ menu.id }}">{{ menu.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      {{ form.bpt_id.label }}
      {{ form.bpt_id(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.public.label }}
      {{ form.public() }}
    </div>

    <div class="form-group">
      {{ form.active.label }}
      {{ form.active() }}
    </div>

    <button type="submit" class="btn btn-green pull-right">Submit</button>
    <p class="pull-right" style="margin-right:10px">* Required</p>
    <div class="clearfix"></div>
  </form>
</div>
{% endblock dash_content %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/bootstrap/bootstrap-datepicker.min.js') }}"></script>

<script type="text/javascript">
  $('#date').datepicker({});
</script>
{% endblock scripts %}

server/dash/templates/dash/base.html
{% extends 'main_base.html' %}
{% set ignore_analytics = True %}

{% block content %}
<div class="wrapper">
  <div class="section-header">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <!-- Remove the .animated class if you don't want things to move -->
          <h1 class="animated slideInLeft"><span>{{ dash_title or 'Admin Dashboard' }}</span></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <!-- Profile Menu -->
      <div class="col-sm-4 col-md-3">
        <div class="user-menu bottom-15">
          <ul>
            <li>
              <a href="{{ url_for('.overview') }}" class="{{ 'active' if dash_menu == 'overview' else '' }}">
                <i class="sign fa fa-area-chart bg-primary"></i> Overview <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
            <li>
              <a href="{{ url_for('.list_images') }}" class="{{ 'active' if dash_menu == 'images' else '' }}">
                <i class="sign fa fa-file-image-o bg-primary"></i> Images <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
            <li>
              <a href="{{ url_for('.list_events') }}" class="{{ 'active' if dash_menu == 'events' else '' }}">
                <i class="sign fa fa-beer bg-primary"></i> Events <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
            <li>
              <a href="{{ url_for('.list_menus') }}" class="{{ 'active' if dash_menu == 'menus' else '' }}">
                <i class="sign fa fa-edit bg-primary"></i> Menus <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
            <li>
              <a href="{{ url_for('.issues') }}" class="{{ 'active' if dash_menu == 'issues' else '' }}">
                <i class="sign fa fa-code bg-primary"></i> Issues <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
            <li>
              <a href="{{ url_for('admin.logout') }}">
                <i class="sign fa fa-sign-out bg-primary"></i> Sign Out <i class="fa fa-chevron-right pull-right"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      {% block dash_content %}{% endblock dash_content %}
    </div>
  </div>
</div>
{% endblock %}

server/dash/templates/dash/edit_event.html
{% extends 'dash/base.html' %}

{% set dash_title = 'Edit Event' %}
{% set dash_menu = 'events' %}

{% block dash_content %}
<div class="col-sm-8 col-md-6">

  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ 'danger' if message[0] == 'error' else 'success' }}">{{ message[1] }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <h3 class="hl">{{ event.name }}</h3>
  <hr>
  <img style="width:100%;border:1px solid #000;" src="{{ event.cover_image.path }}" alt="{{ event.cover_image.name }}">
  <hr>
  <form role="form" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      <label for="event-name">Event name</label>
      <input type="text" class="form-control" name="name" id="event-name" value="{{ event.name }}">
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <input type="text" class="form-control" name="description" id="description" value="{{ event.description }}">
    </div>

    <div class="form-group">
      {{ form.location.label }}
      {{ form.location(class='form-control') }}
    </div>

    <div class="form-group">
      <label for="date">Date</label>
      <input type="text" class="form-control" id="date" value="{{ event.date }}">
    </div>

    <div class="form-group">
      <label for="event_type">Event Type</label>
      <select class="form-control" id="event_type" name="event_type">
        {% for event_type in form.event_type.iter_choices() %}
          <option value="{{ event_type[0] }}" {{ 'selected' if event_type[2] else '' }}>{{ event_type[1] }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="image">Cover Image</label>
      <select class="form-control" id="image" name="image_id">
        {% for image in form.image_id.iter_choices() %}
          <option value="{{ image[0] }}" {{ 'selected' if image[2] else '' }}>{{ image[1] }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="menu">Menu</label>
      <select class="form-control" id="menu" name="menu_id">
        <option value="" selected="selected">No Associated Menu</option>
        {% for menu in menus %}
          <option value="{{ menu.id }}">{{ menu.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      {{ form.bpt_id.label }}
      {{ form.bpt_id(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.public.label }}
      {{ form.public() }}
    </div>

    <div class="form-group">
      {{ form.active.label }}
      {{ form.active() }}
    </div>

    <button type="submit" class="btn btn-green pull-right">Save</button>
  </form>
  <form id="archive-form" method="POST" action="{{ url_for('dash.archive_event', event_id=event.id) }}">
    <button type="submit" class="archive btn btn-red pull-right" style="margin-right:10px">Archive</button>
    <div class="clearfix"></div>
  </form>
</div>
{% endblock dash_content %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/bootstrap/bootbox.min.js') }}"></script>
  <script>
    $(document).on('click', '.archive', function(e) {
        bootbox.confirm('Are you sure you want to archive this event? All associated pictures will be unlinked from this event.', function(result) {
          if (result) {
            $('#archive-form').submit();
          }
        });
        return false;
    });
  </script>
{% endblock scripts %}

server/dash/templates/dash/edit_image.html
{% extends 'dash/base.html' %}

{% set dash_title = 'Edit Image' %}
{% set dash_menu = 'images' %}

{% block dash_content %}
<div class="col-sm-8 col-md-6">

  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ 'danger' if message[0] == 'error' else 'success' }}">{{ message[1] }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <h3 class="hl">Edit {{ image.name }} <small>Added: {{ image.created_at.strftime('%b %d') }}</small></h3>
  <hr>
  <img style="width:100%;border:1px solid #000;" src="{{ image.path }}" alt="{{ image.name }}">
  <h4 class="hl bottom-15">General Information</h4>
  <form role="form" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control') }}
    </div>
    <div class="form-group">
      {{ form.description.label }}
      {{ form.description(class='form-control') }}
    </div>
    <div class="form-group">
      <label for="event">Event</label>
      <select class="form-control" id="event" name="event_id">
        <option value="">No Associated Event</option>
        {% for event in form.event_id.iter_choices() %}
          <option value="{{ event[0] }}" {{ 'selected' if event[2] else '' }}>{{ event[1] }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="menu">Menu</label>
      <select class="form-control" id="menu" name="menu_id">
        <option value="">No Associated Menu</option>
        {% for menu in form.menu_id.iter_choices() %}
          <option value="{{ menu[0] }}" {{ 'selected' if menu[2] else '' }}>{{ menu[1] }}</option>
        {% endfor %}
      </select>
    </div>
    <button type="submit" class="btn btn-green pull-right">Save</button>
  </form>
  <form id="archive-form" method="POST" action="{{ url_for('dash.remove_image', image_id=image.id) }}">
    <button type="submit" class="archive btn btn-red pull-right" style="margin-right:10px">Remove</button>
    <div class="clearfix"></div>
  </form>
</div>
{% endblock dash_content %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/bootstrap/bootbox.min.js') }}"></script>
  <script>
    $(document).on('click', '.archive', function(e) {
        bootbox.confirm('Are you sure you want to remove this image?', function(result) {
          if (result) {
            $('#archive-form').submit();
          }
        });
        return false;
    });
  </script>
{% endblock scripts %}

server/dash/templates/dash/edit_menu.html
{% extends 'dash/base.html' %}

{% set dash_title = 'Edit Menu' %}
{% set dash_menu = 'menus' %}

{% block dash_content %}
<div class="col-sm-8 col-md-6">

  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ 'danger' if message[0] == 'error' else 'success' }}">{{ message[1] }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <h3 class="hl">Edit {{ menu.name }} <small>Added: {{ menu.created_at.strftime('%b %d') }}</small></h3>
  <hr>
  {% if menu.cover_image %}
    <img style="width:100%;border:1px solid #000;" src="{{ menu.cover_image.path }}" alt="{{ menu.cover_image.name }}">
  {% endif %}
  <form role="form" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control') }}
    </div>
    <div class="form-group">
      <label for="event">Event</label>
      <select class="form-control" id="event" name="event_id">
        <option value="">No Associated Event</option>
        {% for event in form.event_id.iter_choices() %}
          <option value="{{ event[0] }}" {{ 'selected' if event[2] else '' }}>{{ event[1] }}</option>
        {% endfor %}
      </select>
    </div>
    <button type="submit" class="btn btn-green pull-right">Save</button>
    <button class="btn btn-red pull-right" style="margin-right:10px">Remove</button>
    <div class="clearfix"></div>
  </form>
</div>
{% endblock dash_content %}

server/dash/templates/dash/issues.html
{% extends 'dash/base.html' %}

{% set dash_title = 'Report Issue' %}
{% set dash_menu = 'issues' %}

{% block dash_content %}
<div class="col-sm-8 col-md-6">

  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ 'danger' if message[0] == 'error' else 'success' }}">{{ message[1] }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <h3 class="hl">Report A Site Issue</h3>
  <hr>
  <form role="form" method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.title.label }}
      {{ form.title(class='form-control') }}
    </div>
    <div class="form-group">
      {{ form.description.label }}
      {{ form.description(class='form-control') }}
    </div>
    <div class="form-group">
      {{ form.priority.label }}
      {{ form.priority(class='form-control') }}
    </div>
    <div class="form-group">
      {{ form.kind.label }}
      {{ form.kind(class='form-control') }}
    </div>
    <button type="submit" class="btn btn-green pull-right">Post</button>
    <div class="clearfix"></div>
  </form>
</div>
{% endblock dash_content %}